config/routes.rb
Rails.application.routes.draw do
  resources :plans

  resources :policies

  resources :exclusions

  resources :coverages

end

app/models/exclusion.rb
class Exclusion < ActiveRecord::Base
	belongs_to :plan
end

app/controllers/exclusions_controller.rb
class ExclusionsController < ApplicationController
  before_action :set_exclusion, only: [:show, :edit, :update, :destroy]

  # GET /exclusions
  # GET /exclusions.json
  def index
    @exclusions = Exclusion.all
  end

  # GET /exclusions/1
  # GET /exclusions/1.json
  def show
  end

  # GET /exclusions/new
  def new
    @exclusion = Exclusion.new
  end

  # GET /exclusions/1/edit
  def edit
  end

  # POST /exclusions
  # POST /exclusions.json
  def create
    @exclusion = Exclusion.new(exclusion_params)

    respond_to do |format|
      if @exclusion.save
        format.html { redirect_to @exclusion, notice: 'Exclusion was successfully created.' }
        format.json { render :show, status: :created, location: @exclusion }
      else
        format.html { render :new }
        format.json { render json: @exclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exclusions/1
  # PATCH/PUT /exclusions/1.json
  def update
    respond_to do |format|
      if @exclusion.update(exclusion_params)
        format.html { redirect_to @exclusion, notice: 'Exclusion was successfully updated.' }
        format.json { render :show, status: :ok, location: @exclusion }
      else
        format.html { render :edit }
        format.json { render json: @exclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exclusions/1
  # DELETE /exclusions/1.json
  def destroy
    @exclusion.destroy
    respond_to do |format|
      format.html { redirect_to exclusions_url, notice: 'Exclusion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exclusion
      @exclusion = Exclusion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exclusion_params
      params.require(:exclusion).permit(:name)
    end
end

app/helpers/exclusions_helper.rb
module ExclusionsHelper
end

app/views/exclusions/_form.html.erb
<%= form_for @exclusion, :html => { :class => "form-horizontal exclusion" } do |f| %>

    <% if @exclusion.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@exclusion.errors.count, "error") %> prohibited this exclusion from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @exclusion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@exclusion[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            exclusions_path, :class => 'btn btn-default' %>

<% end %>

app/views/exclusions/edit.html.erb
<%- model_class = Exclusion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/exclusions/index.html.erb
<%- model_class = Exclusion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @exclusions.each do |exclusion| %>
      <tr>
        <td><%= link_to exclusion.id, exclusion_path(exclusion) %></td>
        <td><%= exclusion.name %></td>
        <td><%=l exclusion.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_exclusion_path(exclusion), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      exclusion_path(exclusion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_exclusion_path,
            :class => 'btn btn-primary' %>

app/views/exclusions/new.html.erb
<%- model_class = Exclusion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/exclusions/show.html.erb
<%- model_class = Exclusion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @exclusion.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              exclusions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_exclusion_path(@exclusion), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              exclusion_path(@exclusion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>