config/routes.rb
Rails.application.routes.draw do
  resources :plans

  resources :policies

  resources :exclusions

  resources :coverages

end

app/models/coverage.rb
class Coverage < ActiveRecord::Base
	belongs_to :plan
end

app/controllers/coverages_controller.rb
class CoveragesController < ApplicationController
  before_action :set_coverage, only: [:show, :edit, :update, :destroy]

  # GET /coverages
  # GET /coverages.json
  def index
    @coverages = Coverage.all
  end

  # GET /coverages/1
  # GET /coverages/1.json
  def show
  end

  # GET /coverages/new
  def new
    @coverage = Coverage.new
  end

  # GET /coverages/1/edit
  def edit
  end

  # POST /coverages
  # POST /coverages.json
  def create
    @coverage = Coverage.new(coverage_params)

    respond_to do |format|
      if @coverage.save
        format.html { redirect_to @coverage, notice: 'Coverage was successfully created.' }
        format.json { render :show, status: :created, location: @coverage }
      else
        format.html { render :new }
        format.json { render json: @coverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coverages/1
  # PATCH/PUT /coverages/1.json
  def update
    respond_to do |format|
      if @coverage.update(coverage_params)
        format.html { redirect_to @coverage, notice: 'Coverage was successfully updated.' }
        format.json { render :show, status: :ok, location: @coverage }
      else
        format.html { render :edit }
        format.json { render json: @coverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coverages/1
  # DELETE /coverages/1.json
  def destroy
    @coverage.destroy
    respond_to do |format|
      format.html { redirect_to coverages_url, notice: 'Coverage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coverage
      @coverage = Coverage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coverage_params
      params.require(:coverage).permit(:name, :liability, :deductible)
    end
end

app/helpers/coverages_helper.rb
module CoveragesHelper
end

app/views/coverages/_form.html.erb
<%= form_for @coverage, :html => { :class => "form-horizontal coverage" } do |f| %>

    <% if @coverage.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@coverage.errors.count, "error") %> prohibited this coverage from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @coverage.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@coverage[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :liability, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :liability, :class => 'form-control' %>
    </div>
    <%= error_span(@coverage[:liability]) %>
  </div>
  <div class="control-group">
    <%= f.label :deductible, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :deductible, :class => 'form-control' %>
    </div>
    <%= error_span(@coverage[:deductible]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            coverages_path, :class => 'btn btn-default' %>

<% end %>

app/views/coverages/edit.html.erb
<%- model_class = Coverage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/coverages/index.html.erb
<%- model_class = Coverage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:liability) %></th>
      <th><%= model_class.human_attribute_name(:deductible) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @coverages.each do |coverage| %>
      <tr>
        <td><%= link_to coverage.id, coverage_path(coverage) %></td>
        <td><%= coverage.name %></td>
        <td><%= coverage.liability %></td>
        <td><%= coverage.deductible %></td>
        <td><%=l coverage.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_coverage_path(coverage), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      coverage_path(coverage),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_coverage_path,
            :class => 'btn btn-primary' %>

app/views/coverages/new.html.erb
<%- model_class = Coverage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/coverages/show.html.erb
<%- model_class = Coverage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @coverage.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:liability) %>:</strong></dt>
  <dd><%= @coverage.liability %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deductible) %>:</strong></dt>
  <dd><%= @coverage.deductible %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              coverages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_coverage_path(@coverage), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              coverage_path(@coverage),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>