config/routes.rb
Rails.application.routes.draw do
  resources :plans

  resources :policies

  resources :exclusions

  resources :coverages

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :policy
	has_many :coverages
	has_many :exclusions

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :shortdesc, :longdesc)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for @plan, :html => { :class => "form-horizontal plan" } do |f| %>

    <% if @plan.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @plan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@plan[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :shortdesc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :shortdesc, :class => 'form-control' %>
    </div>
    <%= error_span(@plan[:shortdesc]) %>
  </div>
  <div class="control-group">
    <%= f.label :longdesc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longdesc, :class => 'form-control' %>
    </div>
    <%= error_span(@plan[:longdesc]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            plans_path, :class => 'btn btn-default' %>

<% end %>

app/views/plans/edit.html.erb
<%- model_class = Plan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plans/index.html.erb
<%- model_class = Plan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:shortdesc) %></th>
      <th><%= model_class.human_attribute_name(:longdesc) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= link_to plan.id, plan_path(plan) %></td>
        <td><%= plan.name %></td>
        <td><%= plan.shortdesc %></td>
        <td><%= plan.longdesc %></td>
        <td><%=l plan.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_plan_path(plan), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      plan_path(plan),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_plan_path,
            :class => 'btn btn-primary' %>

app/views/plans/new.html.erb
<%- model_class = Plan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plans/show.html.erb
<%- model_class = Plan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @plan.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shortdesc) %>:</strong></dt>
  <dd><%= @plan.shortdesc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longdesc) %>:</strong></dt>
  <dd><%= @plan.longdesc %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              plans_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_plan_path(@plan), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              plan_path(@plan),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>