config/routes.rb
Rails.application.routes.draw do
  resources :plans

  resources :policies

  resources :exclusions

  resources :coverages

end

app/models/policy.rb
class Policy < ActiveRecord::Base
	has_many :plans
	has_many :coverages, :through => :plans
	has_many :exclusions, :through => :plans
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
  end

  # GET /policies/new
  def new
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:name, :shortdesc, :longdesc, :monthlypremium, :annualpremium, :policylimit, :exclusionperiod, :minretentionperiod)
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.erb
<%= form_for @policy, :html => { :class => "form-horizontal policy" } do |f| %>

    <% if @policy.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @policy.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :shortdesc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :shortdesc, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:shortdesc]) %>
  </div>
  <div class="control-group">
    <%= f.label :longdesc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longdesc, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:longdesc]) %>
  </div>
  <div class="control-group">
    <%= f.label :monthlypremium, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :monthlypremium, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:monthlypremium]) %>
  </div>
  <div class="control-group">
    <%= f.label :annualpremium, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :annualpremium, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:annualpremium]) %>
  </div>
  <div class="control-group">
    <%= f.label :policylimit, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :policylimit, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:policylimit]) %>
  </div>
  <div class="control-group">
    <%= f.label :exclusionperiod, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :exclusionperiod, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:exclusionperiod]) %>
  </div>
  <div class="control-group">
    <%= f.label :minretentionperiod, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :minretentionperiod, :class => 'form-control' %>
    </div>
    <%= error_span(@policy[:minretentionperiod]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            policies_path, :class => 'btn btn-default' %>

<% end %>

app/views/policies/edit.html.erb
<%- model_class = Policy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/policies/index.html.erb
<%- model_class = Policy -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:shortdesc) %></th>
      <th><%= model_class.human_attribute_name(:longdesc) %></th>
      <th><%= model_class.human_attribute_name(:monthlypremium) %></th>
      <th><%= model_class.human_attribute_name(:annualpremium) %></th>
      <th><%= model_class.human_attribute_name(:policylimit) %></th>
      <th><%= model_class.human_attribute_name(:exclusionperiod) %></th>
      <th><%= model_class.human_attribute_name(:minretentionperiod) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= link_to policy.id, policy_path(policy) %></td>
        <td><%= policy.name %></td>
        <td><%= policy.shortdesc %></td>
        <td><%= policy.longdesc %></td>
        <td><%= policy.monthlypremium %></td>
        <td><%= policy.annualpremium %></td>
        <td><%= policy.policylimit %></td>
        <td><%= policy.exclusionperiod %></td>
        <td><%= policy.minretentionperiod %></td>
        <td><%=l policy.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_policy_path(policy), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      policy_path(policy),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_policy_path,
            :class => 'btn btn-primary' %>

app/views/policies/new.html.erb
<%- model_class = Policy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/policies/show.html.erb
<%- model_class = Policy -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @policy.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shortdesc) %>:</strong></dt>
  <dd><%= @policy.shortdesc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longdesc) %>:</strong></dt>
  <dd><%= @policy.longdesc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:monthlypremium) %>:</strong></dt>
  <dd><%= @policy.monthlypremium %></dd>
  <dt><strong><%= model_class.human_attribute_name(:annualpremium) %>:</strong></dt>
  <dd><%= @policy.annualpremium %></dd>
  <dt><strong><%= model_class.human_attribute_name(:policylimit) %>:</strong></dt>
  <dd><%= @policy.policylimit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exclusionperiod) %>:</strong></dt>
  <dd><%= @policy.exclusionperiod %></dd>
  <dt><strong><%= model_class.human_attribute_name(:minretentionperiod) %>:</strong></dt>
  <dd><%= @policy.minretentionperiod %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              policies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_policy_path(@policy), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              policy_path(@policy),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>